# Base16 eye-cachy - kitty color config
# Scheme by best of all worlds - ultimate comfort blend
background #1d2021
foreground #c5cdd9
selection_background #c5cdd9
selection_foreground #1d2021
url_color #8b92a8
cursor #c5cdd9
cursor_text_color #1d2021
active_border_color #545862
inactive_border_color #282a36
active_tab_background #1d2021
active_tab_foreground #c5cdd9
inactive_tab_background #282a36
inactive_tab_foreground #8b92a8
tab_bar_background #282a36
wayland_titlebar_color #1d2021
macos_titlebar_color #1d2021

# normal
color0 #1d2021
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #89beb7
color7 #c5cdd9

# bright
color8 #545862
color9 #e69875
color10 #282a36
color11 #3c3f4c
color12 #8b92a8
color13 #dde3ed
color14 #d65d0e
color15 #f0f4f8