include ~/.config/kitty/colors.conf

# Font
font_family Mayucode Nerd Font Medium
bold_font Mayucode Nerd Font Bold
italic_font Mayucode Nerd Font Medium Italic
bold_italic_font Mayucode Nerd Font Bold Italic
font_size 13.5

# FIX: Spacing & box drawing
box_drawing_scale 0.001, 1, 1.5, 2
adjust_column_width 0
adjust_line_height 0
disable_ligatures always

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_underline_thickness 2.0
cursor_blink_interval 0
shell_integration enabled
enable_audio_bell no

# Comment dulu cursor_trail untuk testing
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0

# Minimal Tab bar styling
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# BEGIN_KITTY_THEME
# Noctalia
#include current-theme.conf
# END_KITTY_THEME
