exec-once = swww-daemon
exec-once = ~/.config/autostart/autostart
/usr/libexec/xdg-desktop-portal-wlr &
exec-once = waybar -c ~/.config/waybar/mango/config.jsonc -s ~/.config/waybar/mango/style.css &
#exec-once = qs -c noctalia-shell &
