# Root / background
rootcolor=0x1f1f28ff

# Border unfocused
bordercolor=0x363646ff

# Focused window
focuscolor=0x7e9cd8ff

# Urgent
urgentcolor=0xc34043ff

# Maximized window
maximizescreencolor=0x7e9cd8ff