# Root / background
rootcolor=0x1f1f28ff

# Border unfocused
bordercolor=0x090618ff

# Focused window
focuscolor=0xc0a36eff

# Urgent
urgentcolor=0xc34043ff

# Maximized window
maximizescreencolor=0xc0a36eff