# Root / background
rootcolor=0x1d2021ff

# Border unfocused
bordercolor=0x3c3f4cff

# Focused window
focuscolor=0x7fbbb3ff

# Urgent
urgentcolor=0xe67e80ff

# Maximized window
maximizescreencolor=0x7fbbb3ff