source=~/.config/mango/autostart.conf
source=~/.config/mango/colors.conf
source=~/.config/mango/env.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/window-effect.conf
source=~/.config/mango/anim.conf
source=~/.config/mango/layout.conf
source=~/.config/mango/input.conf
source=~/.config/mango/tags.conf

# This sources the noctalia theme

source = /home/cid/.config/mango/noctalia.conf

