# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x101010ff
rootcolor = 0x181818ff
bordercolor = 0x646464ff
focuscolor = 0xffdd33ff
maximizescreencolor = 0x96a6c8ff
urgentcolor = 0xf43841ff
scratchpadcolor = 0x9e95c7ff
globalcolor = 0x806a00ff
overlaycolor = 0x2e477dff
