windowrule=isfloating:1,appid:alacritty-float
windowrule=isfloating:1,appid:foot-float
windowrule=height:600,width:1000,isfloating:1,title:impala
windowrule=isfloating:1,title:bluetui
windowrule=isfloating:1,title:gum-clip
windowrule=height:350,width:500,isfloating:1,title:gum-xr
windowrule=height:500,width:400,isfloating:1,title:gum-flavours
windowrule=height:500,width:400,isfloating:1,title:gum-nl
windowrule=height:500,width:400,isfloating:1,title:gum-menu
windowrule=height:250,width:320,isfloating:1,title:gum-shot
windowrule=height:250,width:320,isfloating:1,title:gum-power
