windowrule=isfloating:1,appid:alacritty-float
windowrule=isfloating:1,title:impala
windowrule=isfloating:1,title:bluetui
windowrule=isfloating:1,title:gum-clip
windowrule=height:500,width:400,isfloating:1,title:gum-flavours
windowrule=height:500,width:400,isfloating:1,title:gum-nighlight
windowrule=height:500,width:400,isfloating:1,title:gum-launcher
windowrule=height:500,width:400,isfloating:1,title:gum-shot
