windowrule=isfloating:1,appid:alacritty-float
windowrule=height:600,width:1000,isfloating:1,appid:kitty-float
windowrule=isfloating:1,appid:com.cid.quicksettings
windowrule=height:600,width:1000,isfloating:1,appid:foot-float
windowrule=height:400,width:400,isfloating:1,appid:org.nmrs.ui
windowrule=height:600,width:1000,isfloating:1,title:impala
windowrule=isfloating:1,title:bluetui

#chrome-extension
windowrule=isfloating:1,appid:chrome-acmacodkjbdgmoleebolmdjonilkdbch  
windowrule=isfloating:1,appid:chrome-gacgndbocaddlemdiaadajmlggabdeod  
windowrule=isfloating:1,appid:chrome-ehgjhhccekdedpbkifaojjaefeohnoea 
windowrule=isfloating:1,appid:chrome-bfnaelmomeimhlpmgjnjophhpkkoljpa 
windowrule=isfloating:1,appid:chrome-mcohilncbfahbmgdjkbpemcciiolgcge 

#gum-selector
windowrule=isfloating:1,title:gum-clip
windowrule=height:400,width:500,isfloating:1,title:gum-xr
windowrule=height:500,width:400,isfloating:1,title:gum-flavours
windowrule=height:500,width:400,isfloating:1,title:gum-nl
windowrule=height:500,width:400,isfloating:1,title:gum-menu
windowrule=height:250,width:320,isfloating:1,title:gum-shot
windowrule=height:250,width:320,isfloating:1,title:gum-power

layerrule=noshadow:1,layer_name:waybar

