# General Configuration
include=~/.config/fuzzel/colors.ini
#include=~/.config/fuzzel/themes/noctalia
# output=<not set>
font=Mayucode:style=Medium:size=9:hintstyle=slight
dpi-aware=auto
prompt=""
icon-theme=Tela-circle-dark
icons-enabled=yes
fields=filename,name,generic
password-character=*
filter-desktop=no
match-mode=fzf
show-actions=no
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
# list-executables-in-path=no

# Layout Settings
anchor=center
lines=10
width=30
tabs=4
horizontal-pad=18
vertical-pad=8
inner-pad=0
image-size-ratio=0.5
line-height=18
letter-spacing=0
layer=top
exit-on-keyboard-focus-loss=yes

# Border Settings
[border]
width=1
radius=0

# dmenu Settings
[dmenu]
# mode=text  # text|index
# exit-immediately-if-empty=no

include=~/.config/fuzzel/themes/noctalia
