# Base16 Kanagawa - foot color config
# xxx
[colors-dark]
background=1f1f28
foreground=c8c093

# Normal colors
regular0=1f1f28 # Black, could also be base01
regular1=c34043 # Red
regular2=76946a # Green
regular3=c0a36e # Yellow
regular4=7e9cd8 # Blue
regular5=957fb8 # Magenta
regular6=6a9589 # Cyan
regular7=c8c093 # White

# Bright colors
bright0=54546d
bright1=ffa066
bright2=2a2a37
bright3=363646
bright4=727169
bright5=c8c093
bright6=d27e99
bright7=f2ecbc