[main]
#include=~/.config/foot/themes/noctalia
include=~/.config/foot/colors.ini
font=Mayucode Nerd Font:style=Medium:size=13.5:hintstyle=none
font-bold=Mayucode Nerd Font:style=Bold:size=13.5:hintstyle=none
font-italic=Mayucode Nerd Font:style=Medium Italic:size=13.5:hintstyle=none
font-bold-italic=Mayucode Nerd Font:style=Bold Italic:size=13.5:hintstyle=none
pad=24x24

[cursor]
blink=true

[mouse]
hide-when-typing=no

#[colors-dark]
#alpha=0.95

