[font]
size = 13

builtin_box_drawing = true

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "SemiBold"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraBold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "SemiBoldItalic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraBoldItalic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
