exec-once = ~/.config/autostart/autostart
#exec-once = sh -c 'pkill -x waybar; sleep 0.2; waybar -c ~/.config/waybar/hypr/config.jsonc -s ~/.config/waybar/hypr/style.css >/dev/null 2>&1 &'
exec-once = waybar -c ~/.config/waybar/hypr/config.jsonc -s ~/.config/waybar/hypr/style.css &

