shell = "bash -c '{}'"

# Waybar
[[items]]
file = "/home/cid/.config/waybar/colors.css"
template = "waybar"
#hook = "command -v waybar >/dev/null && pkill -SIGRTMIN+7 waybar || true"
hook = "pkill -SIGUSR2 waybar || true"
rewrite = true

# Foot
[[items]]
file = "/home/cid/.config/foot/colors.ini"
template = "foot"
hook = "pkill -HUP foot 2>/dev/null || true"
rewrite = true

# Alacritty
[[items]]
file = "/home/cid/.config/alacritty/colors.toml"
template = "alacritty"
rewrite = true

# Fuzzel
[[items]]
file = "/home/cid/.config/fuzzel/colors.ini"
template = "fuzzel"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/theme/colors.lua"
template = "nvim-lua"
subtemplate = "default"
rewrite = true
hook = "[ -S /tmp/nvim-server ] && nvim --server /tmp/nvim-server --remote-send ':lua package.loaded[\"theme.colors\"]=nil; require(\"theme.init\").setup()<CR>' || true"

# Labwc (pakai openbox-3 theme)
#[[items]]
#file = "/home/cid/.local/share/themes/Base16/openbox-3/themerc"
#template = "labwc"
#hook = "command -v labwc >/dev/null && labwc -r || true"
#start = "!! Start flavours"
#end   = "!! End flavours"

[[items]]
file = "/home/cid/.config/fnott/fnott.ini"
start = "# Start flavours (default)"
end   = "# End flavours"
template = "fnott-dark"
#only = ["*dark*","*mocha*","*night*","*noir*"]
hook = "pkill -x fnott || true"

#[[items]]
#file = "/home/cid/.config/fnott/fnott.ini"
#start = "# Start flavours (default)"
#end   = "# End flavours"
#template = "fnott-light"
#only = ["*light*","*latte*","*day*","*dawn*"]
#hook = "pkill -x fnott || true"

# Rofi
[[items]]
file = "/home/cid/.config/rofi/colors.rasi"
template = "rofi"
rewrite = true

[[item]]
file = "~/.config/sway/config.d/colors"
template = "sway"
subtemplate = "colors"
rewrite = true
light = false
hook = "swaymsg reload"

[[items]]
file = "~/.config/niri/colors.kdl"
template = "niri"
subtemplate = "default"
rewrite = true
light = true

[[items]]
file = "~/.config/btop/themes/btop.theme"
template = "btop"
subtemplate = "default"
rewrite = true
light = true

[[items]]
file = "~/.config/superfile/theme/theme.toml"
template = "superfile"
subtemplate = "default"
rewrite = true
light = true

[[items]]
file = "~/.config/mango/colors.conf"
template = "mangowc"
subtemplate = "default"
rewrite = true
hook = "mmsg -d reload_config"

[[items]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/qt5ct/colors/color.conf"
template = "qt"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/qt6ct/colors/color.conf"
template = "qt"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/gtk-3.0/color.css"
template = "gtk"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/gtk-4.0/color.css"
template = "gtk"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/ghostty/themes/colors"
template = "ghostty"
subtemplate = "default"
rewrite = true

[[items]]
file = "~/.config/yazi/theme.toml"
template = "yazi"
subtemplate = "default"
rewrite = true
light = true


