# General Configuration
# output=<nama-output>   # opsional; isi hasil `swaymsg -t get_outputs` kalau mau paksa monitor tertentu
min-width=150
max-width=400
max-height=300
stacking-order=bottom-up
anchor=bottom-right
edge-margin-vertical=8
edge-margin-horizontal=8
notification-margin=8
max-timeout=10
default-timeout=10
idle-timeout=0
# Appearance Settings
border-radius=0
layer=top
border-size=1
padding-vertical=10
padding-horizontal=10
icon-theme=breeze
max-icon-size=40
# Font Settings (disesuaikan untuk 1920x1280)
title-font=Mayucode Nerd Font:size=13:weight=bold
title-format=<u>%a%A</u>
summary-font=Mayucode Nerd Font:size=12:weight=bold
summary-format=<b>%s</b>\n
body-font=Mayucode Nerd Font:size=12:weight=bold
body-format=%b
progress-bar-height=16
# Notification Helpers
selection-helper=fuzzel
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}
# Colors settings
# Start flavours (default)

# === injected by flavours (dark, text light) ===
# Pakai foreground terang biar jelas di background gelap

# Default
background=1f1f28ff
border-color=76946aff
title-color=76946aff
progress-bar-color=76946aff
summary-color=dcd7baff   # terang
body-color=f2ecbcff      # paling terang (putih / abu muda)

[low]
background=1f1f28ff
title-color=7e9cd8ff
summary-color=dcd7baff
body-color=f2ecbcff

[normal]
background=1f1f28ff
title-color=76946aff
summary-color=dcd7baff
body-color=f2ecbcff

[critical]
background=1f1f28ff
title-color=c0a36eff
summary-color=c34043ff
body-color=f2ecbcff
# End flavours
