# Base16 Aamis Dark - alacritty color config
# VYRX

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0f0f0f'
foreground = '0xede4c8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0f0f0f'
cursor = '0xede4c8'

# Normal colors
[colors.normal]
black = '0x0f0f0f'
red = '0xe25d6c'
green = '0xe2be8a'
yellow = '0xe8ab3b'
blue = '0xedb95a'
magenta = '0xe9838f'
cyan = '0x99dbc5'
white = '0xede4c8'

# Bright colors
[colors.bright]
black = '0xcea37f'
red = '0xf4bb54'
green = '0x5e5959'
yellow = '0x706a6a'
blue = '0xe6caab'
magenta = '0xeadccc'
cyan = '0xecb95c'
white = '0xfcfcfc'