# Base16 eye-cachy - alacritty color config
# best of all worlds - ultimate comfort blend

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1d2021'
foreground = '0xc5cdd9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d2021'
cursor = '0xc5cdd9'

# Normal colors
[colors.normal]
black = '0x1d2021'
red = '0xe67e80'
green = '0xa7c080'
yellow = '0xdbbc7f'
blue = '0x7fbbb3'
magenta = '0xd699b6'
cyan = '0x89beb7'
white = '0xc5cdd9'

# Bright colors
[colors.bright]
black = '0x545862'
red = '0xe69875'
green = '0x282a36'
yellow = '0x3c3f4c'
blue = '0x8b92a8'
magenta = '0xdde3ed'
cyan = '0xd65d0e'
white = '0xf0f4f8'