[font]
size = 11.5
builtin_box_drawing = true

[font.normal]
family = "Iosthetic Nerd Font"
style = "Medium"

[font.bold]
family = "Iosthetic Nerd Font"
style = "Bold"

[font.italic]
family = "Iosthetic Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosthetic Nerd Font"
style = "BoldItalic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
